### PR TITLE
Don't loop over all items when item is found

### PR DESCRIPTION
**Pull request by brh**
When true this should break out of the loop

### CODE REVIEW

**Comment by saket** [comment]
Oh wow, that's an embarrassing mistake. Thanks, Bobby!

**Comment by saket** [comment]
By the way, was this your first PR? :)

**Comment by brh** [comment]
On Github, yes

**Comment by saket** [comment]
I meant to an open source project?

**Comment by brh** [comment]
I did a few on bitbucket

**Pull request merged**
